retro_boot_message = r"""
[ SYSTEM BOOTING... ]
[ LOADING GAME ENGINE ███████████████████████▓▓▓▓▓▓▓ ]
[ INITIALIZING MEMORY MODULES... DONE ]
[ CHECKING INPUT DEVICES... DONE ]
[ READY ]

>>> INIT GAME: "RETRO TERMINAL GUESS"
>>> VERSION: RETRO 1.0
>>> PLAYER ONE - INSERT COIN
>>> HIGH SCORE: 0001250
>>> TYPE 'START' TO BEGIN OR 'EXIT' / PRESS 'ENTER' TO QUIT
"""